#!/usr/bin/sh
# Jacob Rodal (https://www.jrodal.dev) (jr6ff@virginia.edu)

backup_arch_btw () {
    if ! cryptsetup luksOpen /dev/sdb1 ArchBackup; then
        exit 1
    fi

    mkdir -p /mnt/ArchBackup
    mount /dev/mapper/ArchBackup /mnt/ArchBackup
    rsync -aAXv / /mnt/ArchBackup --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"}
    umount /mnt/ArchBackup
    rmdir /mnt/ArchBackup
    cryptsetup luksClose ArchBackup
}

# remove notify-after if you do not have this script.
../notify-after/notify-after backup_arch_btw 


